title: AINS6302 AI for Risk Assessment
author: Castalia Institute
only_build_toc_files: true
execute:
  execute_notebooks: force
launch_buttons:
  thebe: true
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
sphinx:
  config:
    html_title: AINS6302 AI for Risk Assessment
